name: icu_parser
description: An extraction of icu parser from the intl_translation package
version: 1.4.0
homepage: https://github.com/sysint64/icu_parser.git

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  petitparser: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.1
